// This program takes two arrays of words, one with cyberpunk themes and one with nouns, and generates a random cyberpunk anime title.  
package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	// DATA
	themes := []string{
		"Cyberspace",
		"Artificial Intelligence",
		"Virtual Reality",
		"Cyborgs",
		"Hacking",
		"Megacorporations",
		"Dystopia",
		"Post-Apocalypse",
		"Transhumanism",
		"Nanotechnology",
	}
	nouns := []string{
		"Blade",
		"Soul",
		"Code",
		"Network",
		"Future",
		"City",
		"Machine",
		"Dream",
		"Darkness",
		"Rebellion",
	}

	// GENERAR UN TITULO RANDOM

	// The time.Now() function returns the current local time, and the UnixNano() method returns the Unix time, the number of nanoseconds elapsed since January 1, 1970 UTC. By using this value as the seed, the sequence of random numbers generated by the Go random number generator will be unique each time the program is run, as the seed will be different depending on the exact time the program is executed.
	rand.Seed(time.Now().UnixNano())

	//  generates a random integer within a specific range. In this case, the range is determined by the length of the themes slice.
	themeIndex := rand.Intn(len(themes))
	nounIndex := rand.Intn(len(nouns))
	title := fmt.Sprintf("%s %s", themes[themeIndex], nouns[nounIndex])

	// MOSTRAR EL TITULO
	fmt.Printf("Generated Title: %s", title)
}
